services:
  lsi-megaraid-storage-manager:
    build: .
    container_name: lsi-megaraid-storage-manager
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - ROOT_PASSWORD=myrootpassword
    network_mode: host
